language: python
python:
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

services:
  - postgresql

before_script:
  - psql -c 'create database populse_db_tests;' -U postgres  

install:
  - apt-get install python-psycopg2
  - python setup.py install .[postgres]

script: python -m populse_db.test
