language: python
python:
# populse_db is not working on Python > 3.5
# The test on 3.6 is removed until the problem gets fixed
#  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

install:
  - python setup.py install

script: python -m populse_db.test
