language: python

os:
  - linux
  - osx

python:
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

services:
  - postgresql

before_script:
  - brew update
  - psql -c 'create database populse_db_tests;' -U postgres  

install:
  - pip install -e .[postgres]
  - pip install codecov

script: 
  - python -m populse_db.test
  - coverage run python/populse_db/test.py

after_success:
- codecov
