language: python
python:
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

services:
  - postgresql

before_script:
  - psql -c 'create database test_populse_db;' -U postgres

install:
    #- pip install psycopg2-binary
    - python setup.py install

script: python -m populse_db.test
