matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py34
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: linux
      language: python  
      python:
        - "3.4"
    - os: linux
      language: python  
      python:
        - "3.5"
    - os: linux
      language: python  
      python:
        - "3.6"

services:
  - postgresql

# osx deps
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python get-pip.py; fi

before_script:
  - psql -c 'create database populse_db_tests;' -U postgres  

install:
  - pip install -e .[postgres]
  - pip install codecov

script: 
  - python -m populse_db.test
  - coverage run python/populse_db/test.py

after_success:
- codecov
