environment:
  
  matrix:
  
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

build: off

services:
  - postgresql

install:
  - "SET PATH=C:\\Program Files\\PostgreSQL\\9.6\\bin\\;%PATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-db\\python\\;%PYTHONPATH%"
  - "%PYTHON%\\python.exe setup.py install"
  - "psql -c 'create database populse_db_tests;' -U postgres"

test_script:
  - "%PYTHON%\\python.exe -m populse_db.test"
