environment:
  
  matrix:
  
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

build: off

install:
  - "echo %cd%"
  - "SET PYTHONPATH=???;%PYTHONPATH%"

test_script:
  - "%PYTHON%\\python.exe -m populse_db.test"
