environment:

  # postgres
  POSTGRES_PORT: tcp://localhost:5432
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_DB: testdb
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6
  PGUSER: postgres
  PGPASSWORD: Password12!
  
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python30"
    - PYTHON: "C:\\Python31"
    - PYTHON: "C:\\Python32"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

services:
  - postgresql96

build_script:
  - "SET PATH=C:\\Program Files\\PostgreSQL\\9.6\\bin\\;%PATH%"
  - psql -c "create database populse_db_tests;" -U postgres

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PYTHONPATH=C:\\projects\\populse-db-6gndf\\python\\;%PYTHONPATH%"
  - "pip install -e .[postgres]"

test_script:
  - "python -m populse_db.test"
